### PR TITLE
Add symfony 3.0 support and use safer constraints

### PR DESCRIPTION
**Pull request by Ener-Getick**
This PR fixes a deprecation and use safer constraints

### CODE REVIEW

**Comment by mmoreram** [comment]
@Ener-Getick Thanks!
A lot of changes...

@vguardiola can you take a look please?

**Comment by Ener-Getick** [comment]
I fixed the tests

**Comment by Ener-Getick** [comment]
ping

**Comment by vguardiola** [comment]
Sorry, I had have a lot of work, I try to review next week. Thanks

**Comment by Ener-Getick** [comment]
No problem, take your time I was just wondering if you forgot this PR.

**Pull request merged**
